// <auto-generated />
using System;
using DataLayer.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataLayer.Model.About", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Abouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 7, 11, 29, 32, 289, DateTimeKind.Utc).AddTicks(7939),
                            Description = "A design and development agency based in London. We create digital products that make people’s lives easier.",
                            IsActive = true,
                            Name = "Header"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 6, 7, 11, 29, 32, 289, DateTimeKind.Utc).AddTicks(7940),
                            Description = "~/images/About/about@2x.jpg",
                            IsActive = true,
                            Name = "Img"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 6, 7, 11, 29, 32, 289, DateTimeKind.Utc).AddTicks(7942),
                            Description = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam,",
                            IsActive = true,
                            Name = "Story"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 6, 7, 11, 29, 32, 289, DateTimeKind.Utc).AddTicks(7943),
                            Description = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam,",
                            IsActive = true,
                            Name = "Mission"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 6, 7, 11, 29, 32, 289, DateTimeKind.Utc).AddTicks(7944),
                            Description = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam,",
                            IsActive = true,
                            Name = "Value"
                        });
                });

            modelBuilder.Entity("DataLayer.Model.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role1",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "role2",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("DataLayer.Model.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasMaxLength(2083)
                        .HasColumnType("nvarchar(2083)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "03ed20eb-4666-4d60-9fc4-c4ac7055a53d",
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECDqIaXTcem8ig1YZzjjLipVlzp5pf+KKTwPyxAFJU1vQNHNEzCEQMh9rmJzE6JqvA==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "~/dist/img/user2-160x160.jpg",
                            SecurityStamp = "4ad4c0e9-fc7e-4dd5-bd95-5d5d04c39c9f",
                            TwoFactorEnabled = false,
                            UserName = "admin@example.com"
                        },
                        new
                        {
                            Id = "user1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b547cd55-023a-4ecf-9f31-012cb30663d6",
                            Email = "user1@example.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@EXAMPLE.COM",
                            NormalizedUserName = "USER1@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAPcV4ABN9pX8t10AAwfvyo6yKPG2B1vVWj2+6sKbDfsCGl51f+4Fo8nYtBanpeOBg==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "~/dist/img/user2-160x160.jpg",
                            SecurityStamp = "ad71d9a7-d7be-43ed-8f59-d564b0bc973a",
                            TwoFactorEnabled = false,
                            UserName = "user1@example.com"
                        },
                        new
                        {
                            Id = "user2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9722a0dd-b7c0-4aa6-a3c6-da7f1a4af60a",
                            Email = "user2@example.com",
                            EmailConfirmed = true,
                            FirstName = "Jane",
                            LastName = "Smith",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER2@EXAMPLE.COM",
                            NormalizedUserName = "USER2@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPyI6LhaUbiZG2bAPGoMHvcfbCw40mSXLKu0ioPiUfFbudV9L3vhkILYAE6SRBtpTw==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "~/dist/img/user2-160x160.jpg",
                            SecurityStamp = "4c82bf39-bf90-416e-9695-29e703fe6bdd",
                            TwoFactorEnabled = false,
                            UserName = "user2@example.com"
                        },
                        new
                        {
                            Id = "user3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f7b471ca-08b7-4583-978c-48be2c986ca0",
                            Email = "user3@example.com",
                            EmailConfirmed = true,
                            FirstName = "Alice",
                            LastName = "Johnson",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER3@EXAMPLE.COM",
                            NormalizedUserName = "USER3@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGRnED98RT7KN1dNwKxkupRZb5jmFMvVxg10OJTaghpW6J4jAJ84tN6WPUSmS1u+1Q==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "~/dist/img/user2-160x160.jpg",
                            SecurityStamp = "8d6ed482-2036-408f-bdbc-cd11446d18db",
                            TwoFactorEnabled = false,
                            UserName = "user3@example.com"
                        },
                        new
                        {
                            Id = "user4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4a4f9c84-5e46-4ce4-acd4-c6f6954b97b3",
                            Email = "user4@example.com",
                            EmailConfirmed = true,
                            FirstName = "Bob",
                            LastName = "Brown",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER4@EXAMPLE.COM",
                            NormalizedUserName = "USER4@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEE1gbOM0NgbJvrT1CHA9rLm5kkpXNfn8NMgpAG1aRGhEHBQeXGyHSj2fSvG2T4S7JQ==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "~/dist/img/user2-160x160.jpg",
                            SecurityStamp = "423d01af-57ff-4386-a231-8227a0569160",
                            TwoFactorEnabled = false,
                            UserName = "user4@example.com"
                        });
                });

            modelBuilder.Entity("DataLayer.Model.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasMaxLength(2083)
                        .HasColumnType("nvarchar(2083)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 30, 11, 7, 55, 0, DateTimeKind.Utc),
                            Date = new DateTime(2020, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Description for Blog 1",
                            IsActive = true,
                            ThumbnailPath = "~/images/Bloggrid/Bloggrid_2@2x.jpg",
                            Title = "Why you must experience design at least once",
                            UserId = "admin1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 30, 11, 7, 55, 0, DateTimeKind.Utc),
                            Date = new DateTime(2020, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Description for Blog 2",
                            IsActive = true,
                            ThumbnailPath = "~/images/Bloggrid/Bloggrid_8@2x.jpg",
                            Title = "Why you must experience design at least once",
                            UserId = "admin1"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 5, 30, 11, 7, 55, 0, DateTimeKind.Utc),
                            Date = new DateTime(2020, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Description for Blog 3",
                            IsActive = true,
                            ThumbnailPath = "~/images/Bloggrid/Bloggrid_7@2x.jpg",
                            Title = "Why you must experience design at least once",
                            UserId = "admin1"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 5, 30, 11, 7, 55, 0, DateTimeKind.Utc),
                            Date = new DateTime(2020, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Description for Blog 4",
                            IsActive = true,
                            ThumbnailPath = "~/images/Bloggrid/Bloggrid_6@2x.jpg",
                            Title = "Why you must experience design at least once",
                            UserId = "admin1"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 5, 30, 11, 7, 55, 0, DateTimeKind.Utc),
                            Date = new DateTime(2020, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Description for Blog 5",
                            IsActive = true,
                            ThumbnailPath = "~/images/Bloggrid/Bloggrid_5@2x.jpg",
                            Title = "Why you must experience design at least once",
                            UserId = "admin1"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 5, 30, 11, 7, 55, 0, DateTimeKind.Utc),
                            Date = new DateTime(2020, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Description for Blog 6",
                            IsActive = true,
                            ThumbnailPath = "~/images/Bloggrid/Bloggrid_4@2x.jpg",
                            Title = "Why you must experience design at least once",
                            UserId = "admin1"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 5, 30, 11, 7, 55, 0, DateTimeKind.Utc),
                            Date = new DateTime(2020, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Description for Blog 7",
                            IsActive = true,
                            ThumbnailPath = "~/images/Bloggrid/Bloggrid_3@2x.jpg",
                            Title = "Why you must experience design at least once",
                            UserId = "admin1"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 5, 30, 11, 7, 55, 0, DateTimeKind.Utc),
                            Date = new DateTime(2020, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Description for Blog 8",
                            IsActive = true,
                            ThumbnailPath = "~/images/Bloggrid/Bloggrid_2@2x.jpg",
                            Title = "Why you must experience design at least once",
                            UserId = "admin1"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 5, 30, 11, 7, 55, 0, DateTimeKind.Utc),
                            Date = new DateTime(2020, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Description for Blog 9",
                            IsActive = true,
                            ThumbnailPath = "~/images/Bloggrid/Bloggrid_1@2x.jpg",
                            Title = "Why you must experience design at least once",
                            UserId = "admin1"
                        });
                });

            modelBuilder.Entity("DataLayer.Model.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("DataLayer.Model.CartDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartDetails");
                });

            modelBuilder.Entity("DataLayer.Model.ClientSay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(2083)
                        .HasColumnType("nvarchar(2083)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ClientSays");
                });

            modelBuilder.Entity("DataLayer.Model.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(2083)
                        .HasColumnType("nvarchar(2083)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("DataLayer.Model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DataLayer.Model.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("DataLayer.Model.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(2083)
                        .HasColumnType("nvarchar(2083)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("DataLayer.Model.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProjectUrl")
                        .IsRequired()
                        .HasMaxLength(2083)
                        .HasColumnType("nvarchar(2083)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Portfolios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Client = "Branding Client",
                            CreatedDate = new DateTime(2024, 5, 30, 11, 7, 55, 0, DateTimeKind.Utc),
                            Description = "A branding project with a simple design approach.",
                            IsActive = true,
                            ProjectUrl = "~/images/Standard_list_blog/Standard_9@2x.jpg",
                            Title = "Simple Design",
                            UserId = "admin1"
                        },
                        new
                        {
                            Id = 2,
                            Client = "Branding Client",
                            CreatedDate = new DateTime(2024, 5, 30, 11, 7, 55, 0, DateTimeKind.Utc),
                            Description = "A branding project with a simple design approach.",
                            IsActive = true,
                            ProjectUrl = "~/images/Standard_list_blog/Standard_8@2x.jpg",
                            Title = "Simple Design",
                            UserId = "admin1"
                        },
                        new
                        {
                            Id = 3,
                            Client = "Branding Client",
                            CreatedDate = new DateTime(2024, 5, 30, 11, 7, 55, 0, DateTimeKind.Utc),
                            Description = "A branding project with a simple design approach.",
                            IsActive = true,
                            ProjectUrl = "~/images/Standard_list_blog/Standard_7@2x.jpg",
                            Title = "Simple Design",
                            UserId = "admin1"
                        },
                        new
                        {
                            Id = 4,
                            Client = "Branding Client",
                            CreatedDate = new DateTime(2024, 5, 30, 11, 7, 55, 0, DateTimeKind.Utc),
                            Description = "A branding project with a simple design approach.",
                            IsActive = true,
                            ProjectUrl = "~/images/Standard_list_blog/Standard_6@2x.jpg",
                            Title = "Simple Design",
                            UserId = "admin1"
                        },
                        new
                        {
                            Id = 5,
                            Client = "Branding Client",
                            CreatedDate = new DateTime(2024, 5, 30, 11, 7, 55, 0, DateTimeKind.Utc),
                            Description = "A branding project with a simple design approach.",
                            IsActive = true,
                            ProjectUrl = "~/images/Standard_list_blog/Standard_5@2x.jpg",
                            Title = "Simple Design",
                            UserId = "admin1"
                        },
                        new
                        {
                            Id = 6,
                            Client = "Branding Client",
                            CreatedDate = new DateTime(2024, 5, 30, 11, 7, 55, 0, DateTimeKind.Utc),
                            Description = "A branding project with a simple design approach.",
                            IsActive = true,
                            ProjectUrl = "~/images/Standard_list_blog/Standard_4@2x.jpg",
                            Title = "Simple Design",
                            UserId = "admin1"
                        },
                        new
                        {
                            Id = 7,
                            Client = "Branding Client",
                            CreatedDate = new DateTime(2024, 5, 30, 11, 7, 55, 0, DateTimeKind.Utc),
                            Description = "A branding project with a simple design approach.",
                            IsActive = true,
                            ProjectUrl = "~/images/Standard_list_blog/Standard_3@2x.jpg",
                            Title = "Simple Design",
                            UserId = "admin1"
                        },
                        new
                        {
                            Id = 8,
                            Client = "Branding Client",
                            CreatedDate = new DateTime(2024, 5, 30, 11, 7, 55, 0, DateTimeKind.Utc),
                            Description = "A branding project with a simple design approach.",
                            IsActive = true,
                            ProjectUrl = "~/images/Standard_list_blog/Standard_2@2x.jpg",
                            Title = "Simple Design",
                            UserId = "admin1"
                        },
                        new
                        {
                            Id = 9,
                            Client = "Branding Client",
                            CreatedDate = new DateTime(2024, 5, 30, 11, 7, 55, 0, DateTimeKind.Utc),
                            Description = "A branding project with a simple design approach.",
                            IsActive = true,
                            ProjectUrl = "~/images/Standard_list_blog/Standard_1@2x.jpg",
                            Title = "Simple Design",
                            UserId = "admin1"
                        });
                });

            modelBuilder.Entity("DataLayer.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2083)
                        .HasColumnType("nvarchar(2083)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 7, 11, 29, 32, 289, DateTimeKind.Utc).AddTicks(7799),
                            Description = "A high-quality flying ninja toy.",
                            ImageUrl = "~/images/Shop/shop@2x.jpg",
                            IsActive = true,
                            Name = "Flying Ninja",
                            Price = 15.00m
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 6, 7, 11, 29, 32, 289, DateTimeKind.Utc).AddTicks(7803),
                            Description = "An invisible ninja toy with stealth mode.",
                            ImageUrl = "~/images/Shop/shop@2x.jpg",
                            IsActive = true,
                            Name = "Invisible Ninja",
                            Price = 20.00m
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 6, 7, 11, 29, 32, 289, DateTimeKind.Utc).AddTicks(7805),
                            Description = "A fast ninja toy with lightning speed.",
                            ImageUrl = "~/images/Shop/shop@2x.jpg",
                            IsActive = true,
                            Name = "Speed Ninja",
                            Price = 18.00m
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 6, 7, 11, 29, 32, 289, DateTimeKind.Utc).AddTicks(7808),
                            Description = "A stealthy ninja toy with night vision.",
                            ImageUrl = "~/images/Shop/shop@2x.jpg",
                            IsActive = true,
                            Name = "Stealth Ninja",
                            Price = 22.00m
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 6, 7, 11, 29, 32, 289, DateTimeKind.Utc).AddTicks(7811),
                            Description = "A shadow ninja toy that blends into the dark.",
                            ImageUrl = "~/images/Shop/shop@2x.jpg",
                            IsActive = true,
                            Name = "Shadow Ninja",
                            Price = 19.00m
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 6, 7, 11, 29, 32, 289, DateTimeKind.Utc).AddTicks(7819),
                            Description = "A samurai ninja toy with a katana.",
                            ImageUrl = "~/images/Shop/shop@2x.jpg",
                            IsActive = true,
                            Name = "Samurai Ninja",
                            Price = 25.00m
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 6, 7, 11, 29, 32, 289, DateTimeKind.Utc).AddTicks(7822),
                            Description = "A rogue ninja toy with dual blades.",
                            ImageUrl = "~/images/Shop/shop@2x.jpg",
                            IsActive = true,
                            Name = "Rogue Ninja",
                            Price = 23.00m
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 6, 7, 11, 29, 32, 289, DateTimeKind.Utc).AddTicks(7825),
                            Description = "A mystic ninja toy with magical powers.",
                            ImageUrl = "~/images/Shop/shop@2x.jpg",
                            IsActive = true,
                            Name = "Mystic Ninja",
                            Price = 28.00m
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 6, 7, 11, 29, 32, 289, DateTimeKind.Utc).AddTicks(7828),
                            Description = "A warrior ninja toy with armor.",
                            ImageUrl = "~/images/Shop/shop@2x.jpg",
                            IsActive = true,
                            Name = "Warrior Ninja",
                            Price = 30.00m
                        });
                });

            modelBuilder.Entity("DataLayer.Model.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "admin1",
                            RoleId = "role2"
                        },
                        new
                        {
                            UserId = "user1",
                            RoleId = "role1"
                        },
                        new
                        {
                            UserId = "user2",
                            RoleId = "role1"
                        },
                        new
                        {
                            UserId = "user3",
                            RoleId = "role1"
                        },
                        new
                        {
                            UserId = "user4",
                            RoleId = "role1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DataLayer.Model.Blog", b =>
                {
                    b.HasOne("DataLayer.Model.ApplicationUser", "User")
                        .WithMany("Blogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataLayer.Model.Cart", b =>
                {
                    b.HasOne("DataLayer.Model.ApplicationUser", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataLayer.Model.CartDetail", b =>
                {
                    b.HasOne("DataLayer.Model.Cart", "Cart")
                        .WithMany("CartDetails")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Model.Product", "Product")
                        .WithMany("CartDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DataLayer.Model.News", b =>
                {
                    b.HasOne("DataLayer.Model.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataLayer.Model.Order", b =>
                {
                    b.HasOne("DataLayer.Model.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataLayer.Model.OrderDetail", b =>
                {
                    b.HasOne("DataLayer.Model.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Model.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DataLayer.Model.Portfolio", b =>
                {
                    b.HasOne("DataLayer.Model.ApplicationUser", "User")
                        .WithMany("Portfolios")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("DataLayer.Model.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DataLayer.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DataLayer.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("DataLayer.Model.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DataLayer.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataLayer.Model.ApplicationUser", b =>
                {
                    b.Navigation("Blogs");

                    b.Navigation("Carts");

                    b.Navigation("Orders");

                    b.Navigation("Portfolios");
                });

            modelBuilder.Entity("DataLayer.Model.Cart", b =>
                {
                    b.Navigation("CartDetails");
                });

            modelBuilder.Entity("DataLayer.Model.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("DataLayer.Model.Product", b =>
                {
                    b.Navigation("CartDetails");

                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
